arm_standalone:
  arm_controller_1:
    type: "ros_controllers::JointPositionController"
    joints:
      - arm_1_joint
    pid: {p: 23, i: 1, d: 6, i_min: -30, i_max: 30}
  arm_controller_2:
    type: "ros_controllers::JointPositionController"
    joints:
      - arm_2_joint
    pid: {p: 23, i: 1, d: 6, i_min: -20, i_max: 20}
  arm_controller_3:
    type: "ros_controllers::JointPositionController"
    joints:
      - arm_3_joint
    pid: {p: 23, i: 1, d: 6, i_min: -20, i_max: 20}
