arm_standalone:
  arm_controller_1:
    type: "ros_controllers::JointPositionController"
    joints:
      - arm_1_joint
    pid: {p: 25, i: 0.5, d: 6, i_min: -4, i_max: 4}
  arm_controller_2:
    type: "ros_controllers::JointPositionController"
    joints:
      - arm_2_joint
    pid: {p: 35, i: 0.3, d: 5, i_min: -3, i_max: 3}
  arm_controller_3:
    type: "ros_controllers::JointPositionController"
    joints:
      - arm_3_joint
    pid: {p: 20, i: 0.3, d: 4, i_min: -33, i_max: 3}
