arm_standalone:
  arm_controller_1:
    type: "ros_controllers::JointPositionController"
    joints:
      - arm_1_joint
    pid: {p: 75, i: 0, d: 3, i_min: -4, i_max: 4}
  arm_controller_2:
    type: "ros_controllers::JointPositionController"
    joints:
      - arm_2_joint
    pid: {p: 70, i: 0, d: 2, i_min: -0.4, i_max: 0.4}
  arm_controller_3:
    type: "ros_controllers::JointPositionController"
    joints:
      - arm_3_joint
    pid: {p: 60, i: 0, d: 2, i_min: -1, i_max: 1}
