arm_standalone:
  arm_controller_1:
    type: "ros_controllers::JointPositionController"
    joints:
      - arm_1_joint
    pid: {p: 2, i: 0.1, d: 0.6, i_min: -2, i_max: 2}
  arm_controller_2:
    type: "ros_controllers::JointPositionController"
    joints:
      - arm_2_joint
    pid: {p: 0.4, i: 0.01, d: 0.18, i_min: -0.4, i_max: 0.4}
  arm_controller_3:
    type: "ros_controllers::JointPositionController"
    joints:
      - arm_3_joint
    pid: {p: 0.5, i: 0.04, d: 0.15, i_min: -1, i_max: 1}
